# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: PR check

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  analyze_and_test:
    name: Analyze & test
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: 8BitJonny/gh-get-current-pr@2.2.0
        id: PR

      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          flutter-version: "3.10.0"

      - name: Prepare flutter project
        run: |
          flutter --version
          flutter pub get

      - name: Analyze project source
        run: |
          flutter analyze lib --fatal-infos
          flutter analyze bin --fatal-infos

      # - name: Run tests
      #   run: flutter test